DATA_PATH = './data'

WINNERS_CSV_FILEPATH = DATA_PATH + '/winners.csv'
PARTICIPANT_CSV_FILEPATH = DATA_PATH + '/parts.csv'
PRIZES_CSV_FILEPATH = DATA_PATH + '/prizes.csv'
CANCELS_TXT_FILEPATH = DATA_PATH + '/cancels.txt'